[package]
name = "mezzo"
version = "0.1.0"
authors = ["Nick Platt <platt.nicholas@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"
spin = "0.3.5"
multiboot2  = { git = "https://github.com/phil-opp/multiboot2-elf64" }
